### ISSUE TITLE
doctests Not Running on Travis/zopetoolkit build (and Broken Under PyPy)

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.catalog#2]
Commit https://github.com/zopefoundation/zope.catalog/commit/2599ef0c65575ca31fb9ecaaddcb0908b9efa45a changed the way doctests are run. Instead of automatically being run for every supported version of python, a specific tox environment is used. This introduces two potential problems.

First, they're only being run under a single version of Python (2.7 in this case)---and that in turn means that breakage for any of the other Python versions goes unreported. In this case, manually running the doctests under PyPy is broken[1](partially a PyPy implementation problem, partially a test problem). Why is this a concern? I suspect it could mean we have higher confidence in our test coverage than is actually warranted. Under zope.catalog 4.0.0, the `zopetoolkit` build is broken under PyPy because of this, but since the doctests no longer run by default with trunk versions of `zope.catalog` this brokenness is hidden.

Second, the use of a distinct environment was not mirrored in `.travis.yml`, so even if the doctests are broken on the one version of Python they're being tested against, it won't be reported automatically.

Would a PR to re-integrate the doctests into the main test suite be welcome? That would take care of both issues. I'm open to exploring this issue more too.

[1] The failures under PyPy. It looks like the `__repr__` differs in more than just the usual `Py` suffix.

```
----------------------------------------------------------------------
File "//zopetoolkit/eggs/zope.catalog-4.0.0-py2.7.egg/zope/catalog/README.txt", line 352, in README.txt
Failed example:
    cat.apply({'hobbies': ['music', 'camping', 'sailing']})
Expected:
    BTrees.IFBTree.IFBucket([(1, 2.0), (2, 1.0), (3, 3.0)])
Got:
    <BTrees.IFBTree.IFBucketPy object at 0x0000000107ce1910>
----------------------------------------------------------------------
File "/zopetoolkit/eggs/zope.catalog-4.0.0-py2.7.egg/zope/catalog/README.txt", line 359, in README.txt
Failed example:
    cat.apply({'hobbies': ['music', 'camping', 'sailing'], 'age': 10})
Expected:
    BTrees.IFBTree.IFBucket([(1, 3.0)])
Got:
    <BTrees.IFBTree.IFBucketPy object at 0x0000000107ce1948>
```

**Comment by tseaver** [comment]
>  I suspect it could mean we have higher confidence in our test coverage than is actually warranted

I don't consider the now-in-Sphinx doctest snippets part of the "test coverage" for the package:  they aren't proper "tests" at all, merely examples which can be verified.  Doctests have problems when used across platforms / versions, largely due to two factors:

- Doctests depend on implementation details (`repr` of objects, hash ordering, etc) which isn't guaranteed to be consistent, and has, historically, broken them.  Adding code to harden them against such problems actually reduces their value as documentation (the examples no longer illustrate "normal" usage).
- The lack of isolation between examples, which is actually a *plus* for the narrative documentation, further reduces the value of doctests as tests:  they tend to fail with enough noise that finding the root cause is harder than with "normal" unit tests.

I'm not opposed to updating them such that they can be exercised with other platforms / Python versions, but don't intend to do that work myself.  When they break due to future changes (e.g., we've seen `repr` change across *minor* Python releases), I'm also likely to disable them rather than try to fix them.

**Comment by jamadden** [comment]
I completely agree with you about the maintenance issues that can arise with doctests. They aren't at all fun to try to workaround.

In my ideal world, every scenario covered in a doctest would also be covered in a unit test. But `zope.component` has doctest failures that are apparently unrelated to repr differences. Specifically, it shows a variation on the `TypeError` that we're discussing [here](https://github.com/zopefoundation/zopetoolkit/pull/2#issuecomment-105989880). Yet all the regular test cases pass. And if the supposition that lookup is failing due to an interaction with proxies is correct, that *seems* like a pretty major functional area that's not covered by unit tests (especially since zope.component provides ZCML specifically for integrating security proxies), which scares me. I don't know how many more of those areas might be out there, but I think there are still a lot of doctest snippets.

Is the right thing to do to port the failing tests over to unit tests? Probably. Is it a lot quicker to run the existing doctests under (at least) PyPy in addition to CPython? Hopefully. Is that attitude why we're in this situation? Possibly :)

I was going to suggest just adding a "pypy-docs" environment to Tox/Travis. That solves the issue of running them under both platforms. It doesn't solve any integration issues that might arise if they're not run by `zopetoolkit` tests. But maybe that's a decent compromise to start? Especially for projects with substantial doctests like `zope.component`? Assuming I can figure out how to fix the underlying issue there.

**Comment by jamadden** [comment]
coveralls tells us [we have 100% test coverage](https://coveralls.io/github/zopefoundation/zope.catalog), and that does run under PyPy. So as far as I'm concerned, I don't consider this to be an issue anymore.
